### PR TITLE
fix: make-token works now

### LINKED ISSUE #691: `hz make-token` is broken in `next`
As of 81402f8:

```
$ hz make-token user
/home/ckastorff/src/github.com/rethinkdb/horizon/cli/src/make-token.js:56
  config = serve.merge_configs(config, serve.read_config_from_file(parsed.project_path,
                                             ^

TypeError: serve.read_config_from_file is not a function
    at Object.processConfig (/home/ckastorff/src/github.com/rethinkdb/horizon/cli/src/make-token.js:56:46)
    at runCommand (/home/ckastorff/src/github.com/rethinkdb/horizon/cli/src/main.js:52:27)
    at Object.<anonymous> (/home/ckastorff/src/github.com/rethinkdb/horizon/cli/src/main.js:70:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
```

### PR DESCRIPTION
**Pull request by deontologician**
Also, it doesnt mess with rethinkdb any more

Fixes #691

---

This change is [Reviewable](https://reviewable.io/reviews/rethinkdb/horizon/729)

### CODE REVIEW

File: cli/src/make-token.js [hunk 1]
```diff
@@ -69,10 +38,10 @@ const processConfig = (parsed) => {
   options = config.default_options();
   options.start_rethinkdb = true;
```
Comment (Tryneus) [inline cli/src/make-token.js]: Pretty sure this can be removed.

**Comment by Tryneus** [comment]
Looks good, just had one small comment.

File: cli/src/make-token.js (hunk 1 above)
Comment (deontologician) [inline cli/src/make-token.js]: I like to keep it, as a reminder of what came before...
