### PR TITLE
hz migrate cleanups

### LINKED ISSUE #756: Gracefully handle parse errors in config.toml
Hi I just did npm install -g horizon@2.0.0-beta-5
Now I am trying to run hz migrate which is not working for me.
I am running the command from the my project folder.

I have tried a lot of variations which haven't worked for me. Can you point out what I am doing wrong:

hz migrate
hz migrate myhorizonapp
hz migrate --project-name myhorizonapp
hz migrate -n myhorizonapp
hz migrate -n "myhorizonapp"
hz migrate "myhorizonapp"
hz migrate ./
hz migrate .hz/config.toml
hz migrate .hz/
hz migrate .

Errors I got:

/Users/username/.nvm/versions/node/v4.2.1/lib/node_modules/horizon/src/migrate.js:119
throw new Error('No project_name given');
^

/Users/username/.nvm/versions/node/v4.2.1/lib/node_modules/horizon/node_modules/toml/lib/parser.js:3946
throw peg$buildException(null, peg$maxFailExpected, peg$maxFailPos);
^
SyntaxError: Expected "#", "E", "\n", "\r", "_", "e", [ \t] or [0-9] but "." found.
Thank you.

### PR DESCRIPTION
**Pull request by deontologician**
fixes #756 
- Parse errors in config.toml are much more informative now:

selection_088
- Added a new `--unportable-backup` flag for hz migrate to allow using `tar` if the python driver isn't installed
- Cleaned up some other errors in `hz migrate` and made them nicer
- Fixed the outer catch for the cli, it was not catching exceptions. (Also, it no longer prints stack traces, since those look really nasty and only help us, not the end user)

---

This change is [Reviewable](https://reviewable.io/reviews/rethinkdb/horizon/757)

### CODE REVIEW

File: cli/src/migrate.js [hunk 1]
```diff
@@ -3,11 +3,11 @@ const chalk = require('chalk');
 const r = require('rethinkdb');
 const Promise = require('bluebird');
 const argparse = require('argparse');
-const child_process = require('child_process');
 const runSaveCommand = require('./schema').runSaveCommand;
 const fs = require('fs');
 const accessAsync = Promise.promisify(fs.access);
 const config = require('./utils/config');
+const procPromise = require('./utils/proc-promise').procPromise;
```
Comment (Tryneus) [inline cli/src/migrate.js:10]: Make `procPromise` the module.export of `proc-promise` rather than a subfield (like the other things in `utils`).

File: cli/src/migrate.js [hunk 2]
```diff
@@ -92,7 +92,18 @@ function processConfig(cmdArgs) {
...
+    help: 'Whether to perform a backup of rethinkdb_data' +
+      ' before migrating',
+  });
+
+  parser.addArgument([ '--unportable-backup' ], {
+    metavar: 'yes|no',
+    default: 'no',
+    constant: 'yes',
+    nargs: '?',
+    help: "Allows creating a backup that is not portable, " +
```
Comment (Tryneus) [inline cli/src/migrate.js]: run eslint, doublequotes are verboten

File: cli/src/migrate.js [hunk 3]
```diff
@@ -92,7 +92,18 @@ function processConfig(cmdArgs) {
     default: 'no',
     constant: 'yes',
     nargs: '?',
-    help: 'Whether to perform a backup of rethinkdb_data before migrating',
+    help: 'Whether to perform a backup of rethinkdb_data' +
+      ' before migrating',
+  });
+
+  parser.addArgument([ '--unportable-backup' ], {
```
Comment (Tryneus) [inline cli/src/migrate.js]: nonportable seems less awkward than unportable

File: cli/src/migrate.js [hunk 4]
```diff
@@ -215,24 +231,48 @@ function makeBackup() {
...
   }
 
-  return new Promise((resolve, reject) => {
-    white('Backing up rethinkdb_data directory');
-    const proc = child_process.spawn('rethinkdb', [
+  if (this.options.unportable_backup) {
+    return unportableBackup()
+  }
+
+  white('Backing up rethinkdb_data directory');
```
Comment (Tryneus) [inline cli/src/migrate.js]: move this above the `unportableBackup` call

File: cli/src/utils/proc-promise.js [hunk 5]
```diff
@@ -0,0 +1,23 @@
...
+  const args = Array.prototype.slice.call(arguments);
+  return new Promise((resolve, reject) => {
+    const proc = childProcess.spawn.apply(childProcess, args);
+    proc.stderr.setEncoding('utf8');
+    proc.stdout.setEncoding('utf8');
+    proc.on('exit', (code) => {
+      if (code === 0) {
+        resolve(proc);
+      } else {
+        reject(new Error(proc.stderr.read()));
```
Comment (Tryneus) [inline cli/src/utils/proc-promise.js]: I think we should include the return code in this error message.

File: cli/src/utils/config.js [hunk 6]
```diff
@@ -333,6 +343,39 @@ const merge_options = (old_options, new_options) => {
   return old_options;
 };
 
+function sourceLine(lineNum, source) {
+  return `${chalk.green(lineNum + ':')} ` +
+    `${chalk.white(source)}`;
+}
+
+function leftPad(length) {
```
Comment (Tryneus) [inline cli/src/utils/config.js]: `new Array(length).fill(' ').join('')`

Comment (Tryneus) [inline cli/src/utils/config.js]: `' '.repeat(length)`

File: cli/src/utils/config.js [hunk 7]
```diff
@@ -333,6 +343,39 @@ const merge_options = (old_options, new_options) => {
...
+          .toString()
+          .split('\n')
+          .slice(e.line-2, e.line+1);
+  return new Error(`\
+There was a syntax error when parsing ${configFilename}
+Check out line ${e.line}, column ${e.column}:
+
+${sourceLine(e.line - 1, context[0])}
+${sourceLine(e.line, context[1])}
+${leftPad(`${e.line}: `.length)}${leftPad(e.column-1)}${chalk.green.bold('^')}
```
Comment (Tryneus) [inline cli/src/utils/config.js]: why leftPad twice in a row?  just add the two numbers

File: cli/src/migrate.js [hunk 8]
```diff
@@ -215,24 +231,48 @@ function makeBackup() {
...
+do a backup before migrating.
+
+You can install the Python driver with the instructions \
+found at:
+http://www.rethinkdb.com/docs/install-drivers/python/
+
+Alternately, you may pass the --unportable-backup flag \
+to hz migrate. This flag uses the tar command to make a \
+backup, but the backup is not safe to use on another \
+machine or to create replicas from.
```
Comment (Tryneus) [inline cli/src/migrate.js]: We should probably mention that:
1) this only works if the `rethinkdb_data` directory is local - that is, they normally run with `--start-rethinkdb`
2) this should not be performed while the `rethinkdb` server is running - the backup could have an inconsistent btree
